terminate called after throwing an instance of 'std::logic_error'
  what():  Triangle doesn't exist
